// frontend/src/views/agent-service.vue
﻿<template>
  <div class="agent-page">
    <div class="tab-bar">
      <button v-for="tab in tabs" :key="tab" class="tab-btn" :class="{ active: activeTab === tab }" @click="activeTab = tab">{{ tab }}</button>
    </div>

    <div class="toolbar">
      <el-input v-model="searchTerm" placeholder="搜索..." :prefix-icon="Search" class="search-input" clearable />
      <div class="spacer" />
      <el-button v-if="activeTab === '工具管理'" type="primary" :icon="Edit">配置工具</el-button>
      <el-button v-if="activeTab === '调用记录'" plain>导出记录</el-button>
    </div>

    <el-row :gutter="16" class="stat-row">
      <el-col :span="6"><el-card shadow="never" class="info-card"><div class="info-card-header"><div class="info-card-icon bg-pink"><el-icon :size="16"><Service /></el-icon></div><span class="info-card-label">今日查询</span><span class="subtag green">正常</span></div><div class="val-row"><span class="val">156</span><span class="badge green-bg">↑ 12%</span></div><div class="foot"><span>目标 200</span><div class="health-bar"><div class="health-bar-fill" style="width:78%" /></div><span>78%</span></div></el-card></el-col>
      <el-col :span="6"><el-card shadow="never" class="info-card"><div class="info-card-header"><div class="info-card-icon bg-orange"><el-icon :size="16"><CircleCheckFilled /></el-icon></div><span class="info-card-label">成功率</span><span class="subtag danger-tag">⚠ 低于阈值</span></div><div class="val-row"><span class="val orange">96%</span><span class="badge red-bg">↓ 2%</span></div><div class="foot"><span>目标 ≥99%</span><div class="health-bar"><div class="health-bar-fill alert" style="width:96%" /></div><span>96%</span></div></el-card></el-col>
      <el-col :span="6"><el-card shadow="never" class="info-card"><div class="info-card-header"><div class="info-card-icon bg-blue"><el-icon :size="16"><Setting /></el-icon></div><span class="info-card-label">可用工具</span><span class="subtag">已配置</span></div><div class="val-row"><span class="val">5</span><span class="badge neutral">较昨日持平</span></div><div class="foot">查询 · 元数据 · 图谱</div></el-card></el-col>
      <el-col :span="6"><el-card shadow="never" class="info-card"><div class="info-card-header"><div class="info-card-icon bg-green"><el-icon :size="16"><Timer /></el-icon></div><span class="info-card-label">平均响应</span><span class="subtag green">良好</span></div><div class="val-row"><span class="val green">1.2s</span><span class="badge neutral">较昨日持平</span></div><div class="foot">最快 0.3s / 最慢 5.6s</div></el-card></el-col>
    </el-row>

    <div v-if="activeTab === 'Agent查询'" class="query-section">
      <el-card shadow="never" class="query-card">
        <div class="query-input-area">
          <el-input v-model="query" type="textarea" :rows="3" placeholder="输入你的问题，例如：上个月销售额最高的前10个客户是谁？" class="query-textarea" />
          <el-button type="primary" size="large" :icon="Promotion" class="send-btn" @click="submitQuery">发送查询</el-button>
        </div>

        <div v-if="showAnswer" class="answer-area">
          <h4>查询结果</h4>
          <div class="answer-sql">生成 SQL: SELECT customer_name, SUM(amount) as total FROM sales_orders WHERE order_date BETWEEN '2026-06-01' AND '2026-06-30' GROUP BY customer_name ORDER BY total DESC LIMIT 10</div>
          <el-table :data="mockResult" stripe size="small" class="result-table">
            <el-table-column label="排名" type="index" width="60" />
            <el-table-column label="客户名称" prop="customer" />
            <el-table-column label="销售额" prop="amount" />
          </el-table>
          <div class="answer-meta">
            <span>数据来源: 销售订单表、客户信息表</span>
            <span>质量状态: <el-tag type="success" size="small" effect="plain">正常</el-tag></span>
          </div>
        </div>
      </el-card>

      <el-card shadow="never" class="suggest-card">
        <h4>示例问题</h4>
        <div class="suggest-list">
          <el-button v-for="q in suggestions" :key="q" plain size="small" class="suggest-btn" @click="query = q">{{ q }}</el-button>
        </div>
      </el-card>
    </div>

    <el-card v-if="activeTab === '工具管理'" shadow="never">
      <el-table :data="agentTools" stripe>
        <el-table-column label="工具名称" prop="name" min-width="160" />
        <el-table-column label="类型" width="100"><template #default="{ row }"><el-tag size="small" effect="plain">{{ row.type }}</el-tag></template></el-table-column>
        <el-table-column label="关联数据集" prop="datasets" min-width="160" />
        <el-table-column label="权限" prop="permission" min-width="130" />
        <el-table-column label="风险" width="80"><template #default="{ row }"><el-tag :type="row.risk === '低' ? 'success' : row.risk === '中' ? 'warning' : 'danger'" size="small" effect="plain">{{ row.risk }}</el-tag></template></el-table-column>
        <el-table-column label="状态" width="80"><template #default><el-tag type="success" size="small" effect="plain">启用</el-tag></template></el-table-column>
        <el-table-column label="操作" width="80" fixed="right"><template #default><el-button link type="primary" size="small">编辑</el-button></template></el-table-column>
      </el-table>
    </el-card>

    <el-card v-if="activeTab === '调用记录'" shadow="never">
      <el-table :data="agentCalls" stripe>
        <el-table-column label="时间" prop="time" width="170" />
        <el-table-column label="用户" prop="user" width="80" />
        <el-table-column label="问题" prop="question" min-width="200" />
        <el-table-column label="工具" prop="tools" width="120" />
        <el-table-column label="数据集" prop="datasets" width="140" />
        <el-table-column label="状态" width="80"><template #default="{ row }"><el-tag :type="row.status === '成功' ? 'success' : 'danger'" size="small" effect="plain">{{ row.status }}</el-tag></template></el-table-column>
        <el-table-column label="操作" width="90" fixed="right"><template #default><el-button link type="primary" size="small">查看详情</el-button></template></el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Search, Edit, Service, CircleCheckFilled, Setting, Timer, Promotion } from '@element-plus/icons-vue'

const activeTab = ref('Agent查询')
const searchTerm = ref('')
const query = ref('')
const showAnswer = ref(false)
const tabs = ['Agent查询', '工具管理', '调用记录']

const suggestions = [
  '上个月销售额最高的前10个客户是谁?',
  '生产线A的平均良品率是多少?',
  '本周有哪些订单状态异常?',
]

const mockResult = [
  { customer: '先锋科技股份有限公司', amount: '¥756,200' },
  { customer: '深圳创新材料集团', amount: '¥623,500' },
  { customer: '上海精密仪器有限公司', amount: '¥498,800' },
]

const agentTools = [
  { name: '数据目录检索', type: '查询工具', datasets: '全部', permission: '所有用户', risk: '低' },
  { name: '受控数据查询', type: '查询工具', datasets: '销售订单表, 生产记录表', permission: '继承用户权限', risk: '中' },
  { name: '质量状态查询', type: '元数据工具', datasets: '全部', permission: '所有用户', risk: '低' },
  { name: '语义检索', type: '查询工具', datasets: '语义对象', permission: '所有用户', risk: '低' },
  { name: '图谱查询', type: '图谱工具', datasets: '关系图谱', permission: '所有用户', risk: '低' },
]

const agentCalls = [
  { time: '2026-06-29 10:15', user: '张三', question: '上个月销售额最高的前10个客户?', tools: '受控查询, 聚合', datasets: '销售订单表, 客户表', status: '成功' },
  { time: '2026-06-29 10:10', user: '李四', question: '生产线A良品率?', tools: '受控查询', datasets: '生产记录表', status: '成功' },
  { time: '2026-06-29 10:05', user: '王五', question: '考勤表空值记录?', tools: '质量查询', datasets: '每日考勤表', status: '失败' },
]

function submitQuery() {
  if (query.value.trim()) showAnswer.value = true
}
</script>

<style lang="scss" scoped>
.agent-page { display: flex; flex-direction: column; gap: 20px; }
.tab-bar { display: flex; gap: 0; border-bottom: 1px solid $color-border; }
.tab-btn { padding: 10px 16px; border: none; background: none; font-size: $font-size-base; color: $color-text-secondary; cursor: pointer; border-bottom: 2px solid transparent; &:hover { color: $color-text-primary; } &.active { color: $color-primary; border-bottom-color: $color-primary; font-weight: $font-weight-medium; } }
.toolbar { display: flex; align-items: center; gap: 12px; }
.search-input { width: 280px; }
.spacer { flex: 1; }
.stat-row { margin: 0 !important; :deep(.el-col) { padding-left: 8px !important; padding-right: 8px !important; } :deep(.el-col:first-child) { padding-left: 0 !important; } :deep(.el-col:last-child) { padding-right: 0 !important; } }
.info-card { :deep(.el-card__body) { padding: 20px; display: flex; flex-direction: column; gap: 8px; } }
.info-card-header { display: flex; align-items: center; gap: 6px; }
.info-card-icon { width: 32px; height: 32px; border-radius: 8px; display: flex; align-items: center; justify-content: center; &.bg-pink { background: #fce7f3; color: #db2777; } &.bg-orange { background: #fff7ed; color: #ea580c; } &.bg-blue { background: #dbeafe; color: $color-primary; } &.bg-green { background: #dcfce7; color: $color-success; } }
.info-card-label { font-size: $font-size-base; color: $color-text-secondary; }
.subtag { font-size: $font-size-xs; padding: 1px 6px; border-radius: 4px; margin-left: auto; white-space: nowrap; background: #f3f4f6; color: $color-text-placeholder; &.green { color: $color-success; background: #f0fdf4; } &.danger-tag { color: $color-danger; background: #fee2e2; border: 1px solid #fecaca; } }
.val-row { display: flex; align-items: baseline; gap: 8px; }
.val { font-size: 28px; font-weight: $font-weight-bold; color: $color-text-primary; &.green { color: $color-success; } &.orange { color: #ea580c; } }
.badge { font-size: $font-size-xs; padding: 1px 6px; border-radius: 4px; &.green-bg { color: $color-success; background: #f0fdf4; } &.red-bg { color: $color-danger; background: #fee2e2; } &.neutral { color: $color-text-placeholder; background: #f3f4f6; } }
.foot { display: flex; align-items: center; gap: 6px; font-size: $font-size-xs; color: $color-text-placeholder; }
.health-bar { flex: 1; height: 4px; background: #f3f4f6; border-radius: 2px; overflow: hidden; }
.health-bar-fill { height: 100%; background: $color-success; border-radius: 2px; &.alert { background: #f97316; } }

.query-section { display: flex; gap: 16px; }
.query-card { flex: 1; }
.query-input-area { display: flex; flex-direction: column; gap: 12px; }
.query-textarea { :deep(textarea) { font-size: $font-size-base; } }
.send-btn { align-self: flex-end; }
.answer-area { border-top: 1px solid $color-border; margin-top: 16px; padding-top: 16px; h4 { margin-bottom: 12px; } }
.answer-sql { padding: 12px; background: #f3f4f6; border-radius: $radius-base; font-family: $font-family-mono; font-size: $font-size-xs; color: $color-text-secondary; margin-bottom: 12px; word-break: break-all; }
.result-table { margin-bottom: 8px; }
.answer-meta { display: flex; gap: 16px; align-items: center; font-size: $font-size-sm; color: $color-text-secondary; }
.suggest-card { width: 280px; flex-shrink: 0; h4 { margin-bottom: 12px; font-size: $font-size-base; } }
.suggest-list { display: flex; flex-direction: column; gap: 8px; }
.suggest-btn { justify-content: flex-start; text-align: left; white-space: normal; height: auto; padding: 8px 12px; }
</style>

// docs/原型设计/src/app/pages/AgentService.tsx
import { useState } from "react";
import { Card } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Textarea } from "../components/ui/textarea";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "../components/ui/table";
import { Bot, Send, Info, CheckCircle2, Search, Edit } from "lucide-react";
import { mockAgentCalls } from "../data/mockData";

const tabs = ["Agent查询", "工具管理", "调用记录"];

const agentTools = [
  { id: "1", name: "数据目录检索", type: "查询工具", datasets: "全部", permission: "所有用户", risk: "低", status: "启用" },
  { id: "2", name: "受控数据查询", type: "查询工具", datasets: "销售订单表, 生产记录表", permission: "继承用户权限", risk: "中", status: "启用" },
  { id: "3", name: "质量状态查询", type: "元数据工具", datasets: "全部", permission: "所有用户", risk: "低", status: "启用" },
  { id: "4", name: "语义检索", type: "查询工具", datasets: "语义对象", permission: "所有用户", risk: "低", status: "启用" },
  { id: "5", name: "图谱查询", type: "图谱工具", datasets: "关系图谱", permission: "所有用户", risk: "低", status: "启用" },
];

export function AgentService() {
  const [activeTab, setActiveTab] = useState("Agent查询");
  const [searchTerm, setSearchTerm] = useState("");
  const [query, setQuery] = useState("");
  const [showAnswer, setShowAnswer] = useState(false);

  const handleSubmit = () => { if (query.trim()) setShowAnswer(true); };

  return (
    <div className="flex flex-col h-full">
      {/* 小标签 */}
      <div className="border-b border-gray-200 px-6">
        <div className="flex gap-0">
          {tabs.map(tab => (
            <button key={tab} onClick={() => setActiveTab(tab)}
              className={`px-4 py-2.5 text-sm border-b-2 transition-colors ${activeTab === tab ? "border-blue-600 text-blue-600 font-medium" : "border-transparent text-gray-500 hover:text-gray-800"}`}>
              {tab}
            </button>
          ))}
        </div>
      </div>

      <div className="flex-1 overflow-auto p-6 flex flex-col gap-4">
        {/* 筛选区 + 操作区 */}
        <div className="flex items-center gap-3">
          <div className="relative max-w-sm flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-gray-400" />
            <Input placeholder="搜索..." value={searchTerm} onChange={e => setSearchTerm(e.target.value)} className="pl-10" />
          </div>
          <div className="ml-auto">
            {activeTab === "工具管理" && <Button><Edit className="size-4 mr-2" />配置工具</Button>}
            {activeTab === "调用记录" && <Button variant="outline">导出记录</Button>}
          </div>
        </div>

        {/* 统计卡片 */}
        <div className="grid grid-cols-4 gap-4">
          <Card className="p-5 flex flex-col justify-between h-[160px]">
            <div className="flex items-center justify-between gap-2">
              <div className="flex items-center gap-2 min-w-0">
                <div className="p-2 bg-pink-100 rounded-lg shrink-0"><Bot className="size-4 text-pink-600" /></div>
                <span className="text-sm text-gray-500 truncate">今日查询</span>
              </div>
              <span className="text-xs text-green-600 bg-green-50 px-1.5 py-0.5 rounded shrink-0 whitespace-nowrap">正常</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-bold text-gray-800 truncate min-w-0">156</span>
              <span className="text-xs text-green-600 bg-green-50 px-1.5 py-0.5 rounded shrink-0 whitespace-nowrap">↑ 12%</span>
            </div>
            <div className="flex items-center gap-2 text-xs text-gray-400">
              <span className="whitespace-nowrap">目标 200</span>
              <div className="flex-1 h-1 bg-gray-100 rounded-full overflow-hidden"><div className="h-full bg-pink-400 rounded-full" style={{width: "78%"}} /></div>
              <span className="whitespace-nowrap">78%</span>
            </div>
          </Card>
          <Card className="p-5 flex flex-col justify-between h-[160px]">
            <div className="flex items-center justify-between gap-2">
              <div className="flex items-center gap-2 min-w-0">
                <div className="p-2 bg-orange-100 rounded-lg shrink-0"><CheckCircle2 className="size-4 text-orange-500" /></div>
                <span className="text-sm text-gray-500 truncate">成功率</span>
              </div>
              <span className="text-xs text-orange-600 bg-orange-50 border border-orange-200 px-1.5 py-0.5 rounded shrink-0 whitespace-nowrap">⚠ 低于阈值</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-bold text-orange-500 truncate min-w-0">96%</span>
              <span className="text-xs text-red-600 bg-red-50 px-1.5 py-0.5 rounded shrink-0 whitespace-nowrap">↓ 2%</span>
            </div>
            <div className="flex items-center gap-2 text-xs text-gray-400">
              <span className="whitespace-nowrap">目标 ≥99%</span>
              <div className="flex-1 h-1 bg-gray-100 rounded-full overflow-hidden"><div className="h-full bg-orange-400 rounded-full" style={{width: "96%"}} /></div>
              <span className="whitespace-nowrap">96/99</span>
            </div>
          </Card>
          <Card className="p-5 flex flex-col justify-between h-[160px]">
            <div className="flex items-center justify-between gap-2">
              <div className="flex items-center gap-2 min-w-0">
                <div className="p-2 bg-blue-100 rounded-lg shrink-0"><Bot className="size-4 text-blue-600" /></div>
                <span className="text-sm text-gray-500 truncate">可用工具</span>
              </div>
              <span className="text-xs text-green-600 bg-green-50 px-1.5 py-0.5 rounded shrink-0 whitespace-nowrap">已启用</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-bold text-gray-800 truncate min-w-0">{agentTools.length}</span>
              <span className="text-xs text-green-600 bg-green-50 px-1.5 py-0.5 rounded shrink-0 whitespace-nowrap">+1 较昨日</span>
            </div>
            <div className="text-xs text-gray-400">查询 · 元数据 · 图谱</div>
          </Card>
          <Card className="p-5 flex flex-col justify-between h-[160px]">
            <div className="flex items-center justify-between gap-2">
              <div className="flex items-center gap-2 min-w-0">
                <div className="p-2 bg-purple-100 rounded-lg shrink-0"><Bot className="size-4 text-purple-600" /></div>
                <span className="text-sm text-gray-500 truncate">可用数据集</span>
              </div>
              <span className="text-xs text-gray-500 bg-gray-100 px-1.5 py-0.5 rounded shrink-0 whitespace-nowrap">持平</span>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-bold text-gray-800 truncate min-w-0">2</span>
              <span className="text-xs text-gray-400 bg-gray-100 px-1.5 py-0.5 rounded shrink-0 whitespace-nowrap">较昨日持平</span>
            </div>
            <div className="text-xs text-gray-400">最后同步: 今日 09:00</div>
          </Card>
        </div>

        {/* 内容区 */}
        {activeTab === "Agent查询" && (
          <div className="grid grid-cols-3 gap-6">
            <div className="col-span-2">
              <Card className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <Bot className="size-6 text-blue-600" />
                  <span className="font-medium">AI 数据查询</span>
                </div>
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4">
                  <div className="flex items-start gap-2">
                    <Info className="size-4 text-blue-600 mt-0.5 shrink-0" />
                    <ul className="text-sm text-blue-700 space-y-1 list-disc list-inside">
                      <li>Agent 只能查询已授权的数据集</li>
                      <li>回答依赖平台数据质量</li>
                      <li>Agent 不会自动写回业务系统</li>
                    </ul>
                  </div>
                </div>
                <Textarea placeholder="例如: 上个月销售额最高的前10个客户是谁?" value={query} onChange={e => setQuery(e.target.value)} rows={4} className="mb-3" />
                <Button onClick={handleSubmit} className="w-full"><Send className="size-4 mr-2" />发送查询</Button>
                {showAnswer && (
                  <div className="border-t border-gray-200 mt-4 pt-4">
                    <div className="flex items-center gap-2 mb-3"><Bot className="size-5 text-blue-600" /><span className="font-medium">Agent 回答:</span></div>
                    <div className="bg-gray-50 rounded-lg p-4 text-sm">
                      <p className="mb-3">根据销售订单表数据,上个月销售额最高的前10个客户如下:</p>
                      <Table>
                        <TableHeader><TableRow><TableHead>排名</TableHead><TableHead>客户ID</TableHead><TableHead>客户名称</TableHead><TableHead>销售额</TableHead></TableRow></TableHeader>
                        <TableBody>
                          <TableRow><TableCell>1</TableCell><TableCell className="font-mono text-xs">CUST-8856</TableCell><TableCell>华东制造有限公司</TableCell><TableCell className="text-green-600">¥1,258,000</TableCell></TableRow>
                          <TableRow><TableCell>2</TableCell><TableCell className="font-mono text-xs">CUST-7745</TableCell><TableCell>南方贸易集团</TableCell><TableCell className="text-green-600">¥985,500</TableCell></TableRow>
                          <TableRow><TableCell>3</TableCell><TableCell className="font-mono text-xs">CUST-9123</TableCell><TableCell>北京科技公司</TableCell><TableCell className="text-green-600">¥756,200</TableCell></TableRow>
                        </TableBody>
                      </Table>
                    </div>
                    <div className="mt-3 space-y-2 text-sm">
                      <div className="flex items-center gap-2"><span className="text-gray-500 min-w-20">数据来源:</span><Badge variant="outline">销售订单表</Badge><Badge variant="outline">客户信息表</Badge></div>
                      <div className="flex items-center gap-2"><span className="text-gray-500 min-w-20">质量状态:</span><Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">正常</Badge></div>
                      <div className="flex items-center gap-2"><span className="text-gray-500 min-w-20">使用工具:</span><span>受控数据查询, 聚合分析</span></div>
                    </div>
                  </div>
                )}
              </Card>
            </div>
            <div>
              <Card className="p-6">
                <div className="font-medium mb-4">当前权限范围</div>
                <div className="space-y-3 mb-6 text-sm">
                  <div><div className="text-gray-500 mb-1">当前用户</div><div>管理员</div></div>
                  <div><div className="text-gray-500 mb-1">可访问角色</div><Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">管理员</Badge></div>
                  <div><div className="text-gray-500 mb-1">可查询数据集</div><div className="flex flex-wrap gap-1 mt-1"><Badge variant="outline">销售订单表</Badge><Badge variant="outline">生产记录表</Badge></div></div>
                </div>
                <div className="border-t border-gray-200 pt-4">
                  <div className="font-medium mb-3">示例问题</div>
                  <div className="space-y-2">
                    {["上个月销售额最高的前10个客户是谁?", "生产线A的平均良品率是多少?", "本周有哪些订单状态异常?"].map(q => (
                      <Button key={q} variant="outline" size="sm" className="w-full justify-start text-left h-auto py-2" onClick={() => setQuery(q)}>
                        <span className="text-sm">{q}</span>
                      </Button>
                    ))}
                  </div>
                </div>
              </Card>
            </div>
          </div>
        )}

        {activeTab === "工具管理" && (
          <div className="bg-white rounded-lg border border-gray-200">
            <Table>
              <TableHeader><TableRow>
                <TableHead>工具名称</TableHead><TableHead>工具类型</TableHead><TableHead>关联数据集</TableHead>
                <TableHead>权限要求</TableHead><TableHead>风险等级</TableHead><TableHead>状态</TableHead>
                <TableHead className="text-right">操作</TableHead>
              </TableRow></TableHeader>
              <TableBody>
                {agentTools.map(tool => (
                  <TableRow key={tool.id}>
                    <TableCell>{tool.name}</TableCell>
                    <TableCell><Badge variant="outline">{tool.type}</Badge></TableCell>
                    <TableCell className="text-sm">{tool.datasets}</TableCell>
                    <TableCell className="text-sm">{tool.permission}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className={tool.risk === "低" ? "bg-green-50 text-green-700 border-green-200" : tool.risk === "中" ? "bg-yellow-50 text-yellow-700 border-yellow-200" : "bg-red-50 text-red-700 border-red-200"}>{tool.risk}</Badge>
                    </TableCell>
                    <TableCell><Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">{tool.status}</Badge></TableCell>
                    <TableCell><div className="flex justify-end"><Button variant="ghost" size="sm">编辑</Button></div></TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}

        {activeTab === "调用记录" && (
          <div className="bg-white rounded-lg border border-gray-200">
            <Table>
              <TableHeader><TableRow>
                <TableHead>时间</TableHead><TableHead>用户</TableHead><TableHead>问题</TableHead>
                <TableHead>使用工具</TableHead><TableHead>使用数据集</TableHead><TableHead>状态</TableHead>
                <TableHead className="text-right">操作</TableHead>
              </TableRow></TableHeader>
              <TableBody>
                {mockAgentCalls.map(call => (
                  <TableRow key={call.id}>
                    <TableCell>{call.time}</TableCell>
                    <TableCell>{call.user}</TableCell>
                    <TableCell className="max-w-xs"><div className="truncate">{call.question}</div></TableCell>
                    <TableCell className="text-sm">{call.tools}</TableCell>
                    <TableCell className="text-sm">{call.datasets}</TableCell>
                    <TableCell>
                      {call.status === "成功"
                        ? <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">成功</Badge>
                        : <Badge variant="outline" className="bg-red-50 text-red-700 border-red-200">{call.status}</Badge>}
                    </TableCell>
                    <TableCell><div className="flex justify-end"><Button variant="ghost" size="sm">查看详情</Button></div></TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </div>
    </div>
  );
}
